// Generated by CoffeeScript 1.9.3
var ReactTemplateCompiler, react_templates;

react_templates = require('react-templates');

module.exports = ReactTemplateCompiler = (function() {
  ReactTemplateCompiler.prototype.brunchPlugin = true;

  ReactTemplateCompiler.prototype.type = 'template';

  ReactTemplateCompiler.prototype.extension = 'rt';

  ReactTemplateCompiler.prototype.pattern = /\.rt/;

  function ReactTemplateCompiler(config) {
    var options, ref, ref1;
    this.config = config;
    options = ((ref = this.config) != null ? (ref1 = ref.plugins) != null ? ref1.reactTemplates : void 0 : void 0) || {};
    this.options = options || {};
  }

  ReactTemplateCompiler.prototype.compile = function(params, callback) {
    var err, output, source;
    source = params.data;
    try {
      output = react_templates.convertTemplateToReact(source, this.options);
    } catch (_error) {
      err = _error;
      console.log("ERROR", err);
      return callback(err.toString());
    }
    return callback(null, {
      data: output
    });
  };

  return ReactTemplateCompiler;

})();
